include $(ARLINKED_INS)/mk/config.mk

PROGRAM = test_can_receiver
SOURCES = receive.ino ../mcp2515_can.cpp

LIBRARIES = $(ARDUINO_LIB_PATH)/SPI/SPI.cpp
INCLUDE_PATHS = ../ $(ARDUINO_LIB_PATH)/SPI

include $(ARLINKED_INS)/mk/make.mk
